package com.bilgeadam.jpa3.exception;

public enum ExceptionCode {

    USERNAME_OR_PASSWORD_NULL,
    USER_IS_NOT_FOUND_ON_DB,
    SQL_EXCEPTION_GENERATED,
    PASSWORDS_ARE_MISMATCHED,
    USER_CANNOT_SAVED,
    CASE_SENSETIVE_EXCEPTION,
    USERNAME_IS_ALREADY_REGISTERED;

}
